ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) 
  ESX = obj
end)

ESX.RegisterUsableItem('B_0_ALOHOMORA_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_0_ALOHOMORA_1',true)
    xPlayer.removeInventoryItem('B_0_ALOHOMORA_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_10_FIRE_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_10_FIRE_1',true)
    xPlayer.removeInventoryItem('B_10_FIRE_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_0_BLOWAROUND-SMOKE_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_0_BLOWAROUND-SMOKE_1',true)
    xPlayer.removeInventoryItem('B_0_BLOWAROUND', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_0_INVITO_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_0_INVITO_1',true)
    xPlayer.removeInventoryItem('B_0_INVITO_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_0_TELEPORT2_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_0_TELEPORT2_1',true)
    xPlayer.removeInventoryItem('B_0_TELEPORT2_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_0_TELEPORT_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_0_TELEPORT_1',true)
    xPlayer.removeInventoryItem('B_0_TELEPORT_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_10_BLOWAROUND-EXPLOSION_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_10_BLOWAROUND-EXPLOSION_1',true)
    xPlayer.removeInventoryItem('B_10_BLOWAROUND', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_10_BLOWAROUND-FIRE_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_10_BLOWAROUND-FIRE_1',true)
    xPlayer.removeInventoryItem('B_10_BLOWAROUND', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_10_BLOW_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_10_BLOW_1',true)
    xPlayer.removeInventoryItem('B_10_BLOW_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_1_STUN_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_1_STUN_1',true)
    xPlayer.removeInventoryItem('B_1_STUN_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_1_WATER_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_1_WATER_1',true)
    xPlayer.removeInventoryItem('B_1_WATER_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_2_REVIVE_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_2_REVIVE_1',true)
    xPlayer.removeInventoryItem('B_2_REVIVE_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_11_AVADAKEDABRA_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_11_AVADAKEDABRA_1',true)
    xPlayer.removeInventoryItem('B_11_AVADAKEDABRA_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_11_BLACKBLOW_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_11_BLACKBLOW_1',true)
    xPlayer.removeInventoryItem('B_11_BLACKBLOW_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_0_WALL_10', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_0_WALL_10',true)
    xPlayer.removeInventoryItem('B_0_WALL_10', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_11_BLACKFIRE_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_11_BLACKFIRE_1',true)
    xPlayer.removeInventoryItem('B_11_BLACKFIRE_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)

ESX.RegisterUsableItem('B_11_IMPERIO_1', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    TriggerClientEvent('Tanulas:OpenBook', playerId, 'B_11_IMPERIO_1',true)
    xPlayer.removeInventoryItem('B_11_IMPERIO_1', 1)
    --xPlayer.showNotification('That was delicious.. right?')
end)
